[package]
name = "geors"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive", "env"] }
geors-api = { version = "0.1.0", path = "crates/geors-api" }
geors-core = { version = "0.1.0", path = "crates/geors-core" }
geors-index = { version = "0.1.0", path = "crates/geors-index" }
geors-rank = { version = "0.1.0", path = "crates/geors-rank" }
geors-update = { version = "0.1.0", path = "crates/geors-update" }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.2", features = ["full"] }
toml = "1.1.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
