# English (UK, US, South Africa, Australia, ...).

[words]
st = ["street", "saint"]
rd = ["road"]
ave = ["avenue"]
av = ["avenue"]
blvd = ["boulevard"]
bd = ["boulevard"]
dr = ["drive", "doctor"]
ln = ["lane"]
pl = ["place"]
sq = ["square"]
cres = ["crescent"]
cl = ["close"]
ct = ["court"]
hwy = ["highway"]
pde = ["parade"]
tce = ["terrace"]
gdns = ["gardens"]
mt = ["mount"]
stn = ["station"]
ctr = ["centre", "center"]
ext = ["extension"]
nth = ["north"]
sth = ["south"]
